### ISSUE TITLE
addgroup: 'root' Error 

### ISSUE THREAD

**Issue by ukrgsm** [a-kryvenko/docker-webserver#1]
Підкажи в чому може бути проблема, при встановленні Nginx отримую помилку

 => ERROR [3/7] RUN addgroup -g 1000 --system root                                                                                                                                                     0.4s
------
 > [3/7] RUN addgroup -g 1000 --system root:
#0 0.365 addgroup: group 'root' in use
------
failed to solve: process "/bin/sh -c addgroup -g ${GID} --system ${USER}" did not complete successfully: exit code: 1

**Comment by a-kryvenko** [comment]
Яка операційна система?

**Comment by ukrgsm** [comment]
Docker встановлений на Debian 11

**Comment by a-kryvenko** [comment]
Спробуй в .env файлі вказати USER=webserver
